version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-z!)c6ob_xlaok234hu*_$!qghek48*i6(uc*7uo2^xv)15vr=b"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
      - "GITHUB_CLIENT_ID=93bf12e2c8bae54b2e56"
      - "GITHUB_API_SECRET=b163b8d122655fe4593d5ce0d97f8f838d88f817"
 
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
