# Generated by Django 3.2.17 on 2023-02-23 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='iso_3166_1_a2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_3166_1_a3',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_3166_1_numeric',
        ),
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
