# Generated by Django 3.2.17 on 2023-02-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20230223_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='country',
            name='iso_3166_1_a2',
            field=models.CharField(default=1, max_length=2, primary_key=True, serialize=False, verbose_name='ISO 3166-1 alpha-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='iso_3166_1_a3',
            field=models.CharField(blank=True, max_length=3, verbose_name='ISO 3166-1 alpha-3'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_3166_1_numeric',
            field=models.CharField(blank=True, max_length=3, verbose_name='ISO 3166-1 numeric'),
        ),
    ]
