"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from environs import Env

env = Env()
env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-z!)c6ob_xlaok234hu*_$!qghek48*i6(uc*7uo2^xv)15vr=b"
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env.bool("DJANGO_DEBUG")


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Django Crispy Forms là một thư viện mã nguồn mở cho phép bạn tạo các form HTML dễ dàng hơn trong Django
    "crispy_forms",
    "crispy_bootstrap5",
    #  quản lý nhiều trang web trên cùng một hệ thống
    # giúp xác định xem một người dùng đang truy cập trang web nào trong hệ thống của bạn
    "django.contrib.sites",
    # Django Allauth là một công cụ mạnh mẽ cho phép bạn tích hợp đăng nhập và đăng ký qua các dịch vụ xác thực như Google, Facebook, Twitter và nhiều dịch vụ khác vào trang web của bạn
    "allauth",
    "allauth.account",
    # Sử dụng lớp cấu hình mặc định của ứng dụng
    "pages",
    # Sử dụng lớp cấu hình riêng của bạn cho ứng dụng
    "accounts.apps.AccountsConfig",
    # "accounts",
]

# django-crispy-forms
# xác định các bộ template mà bạn muốn sử dụng
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# xác định bộ template mà bạn muốn sử dụng mặc định cho toàn bộ form trong ứng dụng của bạn
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ID của trang web mà bạn đang xây dựng trong hệ thống các trang web của mình.
SITE_ID = 1
AUTHENTICATION_BACKENDS = (
    # xác thực một người dùng
    "django.contrib.auth.backends.ModelBackend",
    # xác thực cụ thể (đăng nhập qua e-mail)
    "allauth.account.auth_backends.AuthenticationBackend",  # new
)

# django-allauth config
# tùy chọn hộp “Remember Me” sẽ đặt thành True và không hiển thị
ACCOUNT_SESSION_REMEMBER = True
#  chỉ yêu cầu mật khẩu một lần khi đăng ký
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
# chỉ đăng nhập bằng email
ACCOUNT_USERNAME_REQUIRED = False  # new
ACCOUNT_AUTHENTICATION_METHOD = "email"  # new
ACCOUNT_EMAIL_REQUIRED = True  # new
ACCOUNT_UNIQUE_EMAIL = True  # new
# điều hướng đến "home" khi đăng nhập thành công
LOGIN_REDIRECT_URL = "home"
# điều hướng đến "home" khi đăng xuất thành công
ACCOUNT_LOGOUT_REDIRECT_URL = "home"


# yêu cầu Django xuất bất kỳ email nào tới bảng điều khiển dòng lệnh
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # new

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "postgres",
#         "USER": "postgres",
#         "PASSWORD": "postgres",
#         "HOST": "db",  # set in docker-compose.yml
#         "PORT": 5432,  # default postgres port
#     }
# }
DATABASES = {
    "default": env.dj_db_url("DATABASE_URL", default="postgres://postgres@db/postgres")
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
# danh sách các đường dẫn thư mục đến những tập tin tĩnh (CSS, JavaScript, hình ảnh)
STATICFILES_DIRS = [BASE_DIR / "static"]

# Một danh sách các thư mục chứa các tập tin tĩnh (static files) mà bạn muốn Django tìm kiếm
# khi bạn sử dụng các lệnh collectstatic hoặc khi sử dụng {% static %} trong các mẫu Django.
# Khi bạn muốn sử dụng máy chủ tĩnh để phân phối tập tin tĩnh của bạn
STATIC_ROOT = BASE_DIR / "staticfiles"
# chuỗi cấu hình cho lớp cung cấp lưu trữ tĩnh
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"  # new


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.CustomUser"

DEFAULT_FROM_EMAIL = "huynhlevu5598@gmail.com"
